export default function Privacy() {
  return (
    <div className="qm-shell min-h-screen">
      <div className="qm-wrap">
        <div className="qm-panel p-6">
          <h1 className="qm-about__title">Privacy Policy</h1>

          <p className="qm-about__text">
            Quantum Mail respects your privacy and is committed to protecting it.
          </p>

          <p className="qm-about__text">
            Quantum Mail does not require registration and does not collect
            personal information such as names, passwords, or permanent email
            addresses.
          </p>

          <p className="qm-about__text">
            Emails generated by Quantum Mail are temporary and automatically
            deleted after a short period of time.
          </p>

          <p className="qm-about__text">
            Third-party vendors, including Google, may use cookies to serve ads
            based on a user's prior visits to this website.
          </p>

          <p className="qm-about__text">
            Temporary emails and received messages are automatically deleted and
            are not stored permanently.
          </p>

          <p className="qm-about__text">
            If you have any questions regarding this Privacy Policy you can
            contact us through the Contact page.
          </p>
        </div>
      </div>
    </div>
  );
}
